#!/usr/bin/env python

import sys
sys.path.append("/Users/ruggeri/repos/ruggeri/tech-notes/lib")

from make_latex import run
from pathlib import Path

SOURCE_PATHS = [Path(f) for f in [
  "./direct-sum-vs-direct-product.tex"
]]

run(SOURCE_PATHS)
