#!/usr/bin/env python

import sys
sys.path.append("/Users/ruggeri/repos/ruggeri/tech-notes/lib")

from make_latex import clean
from pathlib import Path

SOURCE_PATHS = [Path(f) for f in [
  "./music-theory.tex"
]]

for p in SOURCE_PATHS:
  clean(p)
